### ISSUE TITLE
VG_

### ISSUE THREAD

**Issue by majid0jalili** [CMU-SAFARI/compression#1]
Hi,

Does existence of VG_ directives in the script is necessary? I mean, my code did not compile with this directive. I removed all VG_ in the code and it compiled successfully.  Is this a problem?

**Comment by gpekhimenko** [comment]
Hi,

You are absolutely right. VG directives are from the simulator I used this
code with, where all major system calls were redefined.
You can just remove those VG, either remove them from the code, or use a
proper define, to replace all of them with empty line.

Good luck,
Gena

On Mon, May 4, 2015 at 3:41 AM, majid169 notifications@github.com wrote:

> Hi,
> 
> Does existence of VG_ directives in the script is necessary? I mean, my
> code did not compile with this directive. I removed all VG_ in the code and
> it compiled successfully. Is this a problem?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CMU-SAFARI/BDICompression/issues/1.

## 

Best Regards,
Gennady Pekhimenko, MSc.
PhD Student, CSD, Carnegie Mellon University
5000 Forbes Ave, Gates Building, Pittsburgh PA 15213

**Comment by siddu244** [comment]
What is the output after compiling this code.?

**Comment by gpekhimenko** [comment]
This code is supposed to be used as an API inside your own code to perform the compression with different compression algorithms. It doesn't generate a standalone binary.
